export enum ECourseActionTypes {
    GET_CATEGORY_AND_COURSE_LIST = "GET_CATEGORY_AND_COURSE_LIST",
    GET_COURSE_BY_CATEGORY = "GET_COURSE_BY_CATEGORY",
    GET_COURSE_DETAIL = "GET_COURSE_DETAIL",
}