export enum ELoadingActionTypes {
  OPEN_BUTTON_LOADING = "OPEN_BUTTON_LOADING",
  CLOSE_BUTTON_LOADING = "CLOSE_BUTTON_LOADING",
  OPEN_PAGE_LOADING = "OPEN_PAGE_LOADING",
  CLOSE_PAGE_LOADING = "CLOSE_PAGE_LOADING",
  OPEN_DATA_LOADING = "OPEN_DATA_LOADING",
  CLOSE_DATA_LOADING = "CLOSE_DATA_LOADING",
}
