export enum EModalActionTypes {
  OPEN_CONSULT_MODAL = "OPEN_CONSULT_MODAL",
  OPEN_SHIPMENT_MODAL = "OPEN_SHIPMENT_MODAL",
  OPEN_PAYMENT_MODAL = "OPEN_PAYMENT_MODAL",
  OPEN_ORDER_MODAL = "OPEN_ORDER_MODAL",
  OPEN_REGISTER_MODAL = "OPEN_REGISTER_MODAL",
  OPEN_PASSWORD_MODAL = "OPEN_PASSWORD_MODAL",
  CLOSE_CONSULT_MODAL = "CLOSE_CONSULT_MODAL",
  CLOSE_SHIPMENT_MODAL = "CLOSE_SHIPMENT_MODAL",
  CLOSE_PAYMENT_MODAL = "CLOSE_PAYMENT_MODAL",
  CLOSE_ORDER_MODAL = "CLOSE_ORDER_MODAL",
  CLOSE_REGISTER_MODAL = "CLOSE_REGISTER_MODAL",
  CLOSE_PASSWORD_MODAL = "CLOSE_PASSWORD_MODAL",
}
