export enum EProductActionTypes {
  GET_CATEGORY_LIST = "GET_CATEGORY_LIST",
  GET_PRODUCT_LIST = "GET_PRODUCT_LIST",
  GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY",
  GET_PRODUCT_BY_PRODUCER = "GET_PRODUCT_BY_PRODUCER",
  GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL",
  GET_PRODUCT_BY_FREE_TEXT = "GET_PRODUCT_BY_FREE_TEXT",
}
