const EngLang = {
  headerMenu: {
    home: "Home",
    product: "Product",
    course: "Course",
    aboutUs: "About Us",
    contact: "Contact",
    computer: "Computer",
    electronics: "Electronics",
    accessories: "PC Accessories",
    printer: "PRINTER",
    monitor: "MONITOR",
    faxMachine: "FAX MACHINE",
    cpu: "CPU",
    ram: "RAM",
    hdd: "HDD",
    ssd: "SSD",
    vga: "VGA - GRAPHICS CARD",
    psu: "PSU - POWER SUPLLY UNIT",
    mainboard: "MAINBOARD",
    mindsetPrograming: "Mindset Programing",
    mobilePrograming: "Mobile Programing",
    fullstackPrograming: "Fullstack Programing",
    backendPrograming: "Backend Programing",
    fronendPrograming: "Frontend Programing",
    signIn: "Sign in",
    signUp: "Sign up",
    accountSetting: "Account Setting",
    logOut: "Log out",
  },
  home: {
    carousel: {
      slideTitle_1: "PC ACCESSORIES",
      slideContent_1: "Build your own PC",
      slideTitle_2: "COURSE",
      slideContent_2: "Gain knownledge for yourself",
      slideTitle_3: "MOVIES",
      slideContent_3: "Enjoys with your family",
    },
    consultation: {
      consultation: "Consultation",
      signUpConsultation: "Sign up for Consulation",
      modal: {
        title: "User Information",
        name: "Name",
        email: "Email",
        phone: "Phone",
        note: "Thank you for your interest, we have received your information, we will contact you soon. In the meantime, please visit our website for more information."
      }
    },
    categories: {
      title_1: "Products",
      title_2: "Courses",
      title_3: "Movies",
      content_1:
        "Trusted by many partners, Terra Nova specialize in supplying and distributing all kinds of items such as electronics, essential appliances, computer accessories, etc.",
      content_2:
        "With many attractive courses, you can choose the one that's suit for you. Terra Nova will satisfy you.",
      content_3:
        "Terra Nova will give you attractive movies from many countries.",
    },
    banner: {
      title_1: "PC ACCESSORIES",
      title_2: "COURSES",
      title_3: "MOVIES",
      content_1: "Build your own PC",
      content_2: "Gain knownledge for yourself",
      content_3: "Enjoy with your family",
      cpu: "Processor Unit (CPU)",
      mainboard: "Mainboard",
      ram: "Random Access Memory (RAM)",
      hdd: "Hard Disk Drive (HDD, SSD)",
      vga: "Graphics Card (VGA)",
      psu: "Power Supply Units (PSU)",
      monitor: "Monitor",
      mindset: "Mindset Programing",
      frontend: "FrontEnd Programing",
      backend: "Backend Programing",
      mobile: "Mobile Programing",
      fullstack: "Fullstack Programing",
    },
    partners: {
      title: "Our partners",
      asusContent: `ASUSTek Computer Inc. Chinese: 華碩電腦股份有限公司; pinyin: Huáshuò Diànnǎo Gǔfèn Yǒuxiàn Gōngsī; stylised as ASUSTeK or ASUS) is a Taiwanese multinational computer and phone hardware and electronics company headquartered in Beitou District, Taipei, Taiwan. Its products include desktop computers, laptops, netbooks, mobile phones, networking equipment, monitors, wi-fi routers, projectors, motherboards, graphics cards, optical storage, multimedia products, peripherals, wearables, servers workstations, and tablet PCs. The company is also an original equipment manufacturer (OEM).`,
      gigaContent: `Gigabyte Technology (branded as GIGABYTE or sometimes GIGA-BYTE; formally GIGA-BYTE Technology Co., Ltd.) is a Taiwanese manufacturer and distributor computer hardware. Gigabyte's principal business is motherboards. It shipped 4.8 million motherboards in the first quarter of 2015, which allowed it to become the leading motherboard vendor. Gigabyte also manufactures custom graphics cards and laptop computers (including thin and light laptops under its Aero sub-brand). In 2010, Gigabyte was ranked 17th in "Taiwan's Top 20 Global Brands" by the Taiwan External Trade Development Council.`,
      msiContent: `Micro-Star International Co., Ltd (MSI; Chinese: 微星科技股份有限公司) is a Taiwanese multinational information technology corporation headquartered in New Taipei City, Taiwan. It designs, develops and provides computer hardware, related products and services, including laptops, desktops, motherboards, graphics cards All-in-One PCs, servers, industrial computers, PC peripherals, car infotainment products, etc.`,
      asrockContent: `ASRock Inc. (Chinese: 華擎科技股份有限公司; pinyin: Huáqíng Kējì Gǔfèn Yǒuxiàn Gōngsī) is a Taiwanese manufacturer of motherboards, industrial PCs and home theater PCs (HTPC). Led by Ted Hsu, it was founded in 2002 and is currently owned by Taiwanese electronics company Pegatron.`,
      kingstonContent: `Kingston Technology Corporation is an American multinational computer technology corporation that develops, manufactures, sells and supports flash memory products and other computer-related memory products, as well as the HyperX gaming division (now owned by HP). Headquartered in Fountain Valley, California, United States, Kingston Technology employs more than 3,000 employees worldwide as of Q1 2016. The company has manufacturing and logistics facilities in the United States, United Kingdom, Ireland, Taiwan, and China.`,
      westernContent: `Western Digital Corporation (WDC, commonly known as Western Digital or WD) is an American computer hard disk drive manufacturer and data storage company, headquartered in San Jose, California. It designs, manufactures and sells data technology products, including storage devices, data center systems and cloud storage services.
      Western Digital has a long history in the electronics industry as an integrated circuit maker and a storage products company. It is one of the largest computer hard disk drive manufacturers, along with producing SSDs and flash memory devices. Its competitors include the data management and storage companies Seagate Technology and Micron Technology`,
      viewContent: `ViewSonic Corporation is a privately held multinational electronics company with headquarters in Brea, California, United States and a research & development center in New Taipei City, Taiwan. ViewSonic specializes in visual display hardware—including liquid-crystal displays, projectors, and interactive whiteboards—as well as digital whiteboarding software. The company trades in three key markets: education, enterprise, and entertainment. ViewSonic is a nationally certified minority-owned business by the Southern California Minority Supplier Development Council.`,
      lgContent: `LG Corporation (or LG Group) (Korean: 엘지), formerly Lucky-Goldstar from 1983 to 1995 (Korean: Leokki Geumseong; Korean: 럭키금성; Hanja: 樂喜金星), is a South Korean multinational conglomerate corporation founded by Koo In-hwoi and managed by successive generations of his family. It is the fourth-largest chaebol in South Korea. Its headquarters are in the LG Twin Towers building in Yeouido-dong, Yeongdeungpo District, Seoul. LG makes electronics, chemicals, and telecommunications products and operates subsidiaries such as LG Electronics, Zenith, LG Display, LG Uplus, LG Innotek, LG Chem, and LG Energy Solution in over 80 countries.`,
      samsungContent: `The Samsung Group (or simply Samsung) (Korean: 삼성) is a South Korean multinational manufacturing conglomerate headquartered in Samsung Town, Seoul, South Korea. It comprises numerous affiliated businesses, most of them united under the Samsung brand, and is the largest South Korean chaebol (business conglomerate). As of 2020, Samsung has the 8th highest global brand value. Samsung was founded by Lee Byung-chul in 1938 as a trading company. Over the next three decades, the group diversified into areas including food processing, textiles, insurance, securities, and retail. Samsung entered the electronics industry in the late 1960s and the construction and shipbuilding industries in the mid-1970s; these areas would drive its subsequent growth. Following Lee's death in 1987, Samsung was separated into five business groups: Samsung Group, Shinsegae Group, CJ Group and Hansol Group, and Joongang Group.`,
    },
    achievement: {
      branches: "Branches",
      customers: "Customers",
      partners: "Partners",
    },
  },
  productList: {
    title: "PRODUCT",
  },
  productDetail: {
    generalInfo: "General information",
    producer: "Producer",
    warranty: "Warranty",
    status: "Status",
    price: "Price",
    specs: "Specifications",
    comments: "Comments",
    related: "Related products",
  },
  footer: {
    partners: "Parters",
    socials: "Socials",
    company: "TERRA NOVA TRADING COMPANY",
    address_1:
      "Branches 1: 102 Nguyen Dinh Chinh Str, Ward 15, District Phu Nhuan, HCMC",
    address_2:
      "Branches 2: 12B Nguyen Huu Canh Str, Ward 19, District Binh Thanh, HCMC",
  },
  productCarts: {
    title: "Cart",
    summaryTitle: "General infomation",
    paymentType: "Choose your payment type",
    payment: "Payment",
    cash: "Cash",
    note: "Note",
    vib: "VIB - Bank",
    price: "Price",
    shipment: "Shipment",
    total: "Total",
    vat: "VAT 10%",
    totalPay: "Total pay",
    noShipment: "Received in store",
    delivery: "Delivery",
    receivedType: "Please choose recevied type",
  },
  time: {
    day: "day",
    month: "month",
    year: "year",
    days: "days",
    months: "months",
    years: "years",
    Day: "Day",
    Month: "Month",
    Year: "Year",
    Days: "Days",
    Months: "Months",
    Years: "Years",
  },
  status: {
    new: "New",
  },
  button: {
    submit: "Submit",
    seeMore: "See more",
    addToCart: "Add to cart",
    buyProduct: "Buy product",
    addProduct: "Add product",
    update: "Update",
    payment: "Payment",
  },
  noData: {
    data: "No data founded",
    product: "No product yet",
  },
  carts: {
    slots: "slots",
  },
  toastMessages: {
    success: {
      addToCart: "Add to carts successed",
      updateCart: "Update successed",
      removeCart: "Remove successed",
      createOrder: "Payment successed",
      signIn: "Sign in successed",
      signUp: "Sign up successed",
    },
    error: {
      addToCart: "Add to carts failed",
      updateCart: "Update failed",
      removeCart: "Remove failed",
      createOrder: "Payment failed",
      signIn: "Account or password incorrect",
      signUp: "Sign up failed",
    },
  },
  validateMessages: {
    required: "Please fulfill this field",
    date: "Please choose a date",
    phone: "Phone is invalid",
    email: "Email is invalid",
    password: "Password is incorrect",
    gender: "Please choose your gender",
    whiteSpace: "should not have whitespace character",
  },
  form: {
    account: "Account",
    password: "Password",
    passConfirm: "Password confirm",
    name: "Name",
    firstName: "First name",
    lastName: "Last name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    birthday: "Birthday",
    gender: "Gender",
    male: "Male",
    female: "Female",
    comment: "Comment",
    personalInfo: "Personal information",
    signIn: "Sign in",
    signUp: "Sign up",
    dontHaveAcc: "Don't have account?",
    haveAcc: "Already have account?",
    search: "Search",
    note: "Note",
  },
  tableHeader: {
    number: "No.",
    image: "Image",
    name: "Name",
    productName: "Name",
    amount: "Amount",
    price: "Price",
    features: "Features",
    description: "Description",
  },
  pagination: {
    showing: "Showing",
    of: "of",
    results: "results"
  }
};

export type LangENG = typeof EngLang; 

export default EngLang;
