import {
  EInventoryStatus,
  EProducer,
  EProductStatus,
  EProductType,
  EProfit,
} from "./../models/Product/index";
import { EPaymentTypes, EShipmentType } from "../models/Order";
import { EWard, EDistrict, EProvince } from "./../models/Shipment";

export const optionsEng = {
  province: [
    { label: "Ho Chi Minh", value: EProvince.HCM },
    { label: "Ha Noi", value: EProvince.HN },
  ],
  HCM: {
    ward: [
      { label: "1", value: EWard.one },
      { label: "2", value: EWard.two },
      { label: "3", value: EWard.three },
      { label: "4", value: EWard.four },
      { label: "5", value: EWard.five },
      { label: "6", value: EWard.six },
      { label: "7", value: EWard.seven },
      { label: "8", value: EWard.eight },
      { label: "9", value: EWard.nine },
      { label: "10", value: EWard.ten },
      { label: "11", value: EWard.eleven },
      { label: "12", value: EWard.twelve },
      { label: "13", value: EWard.thirteen },
      { label: "14", value: EWard.fourteen },
    ],
    district: [
      { label: "1", value: EDistrict.one },
      { label: "2", value: EDistrict.two },
      { label: "3", value: EDistrict.three },
      { label: "4", value: EDistrict.four },
      { label: "5", value: EDistrict.five },
      { label: "6", value: EDistrict.six },
      { label: "7", value: EDistrict.seven },
      { label: "8", value: EDistrict.eight },
      { label: "9", value: EDistrict.nine },
      { label: "10", value: EDistrict.ten },
      { label: "11", value: EDistrict.eleven },
      { label: "12", value: EDistrict.twelve },
    ],
  },
  HN: {
    ward: [
      { label: "Hoan Kiem", value: EWard.hoanKiem },
      { label: "Dong Da", value: EWard.dongDa },
      { label: "Ba Dinh", value: EWard.baĐinh },
      { label: "Hai Ba Trung", value: EWard.haiBaTrung },
      { label: "Hoang Mai", value: EWard.hoangMai },
      { label: "Thanh Xuan", value: EWard.thanhXuan },
      { label: "Long Bien", value: EWard.longBien },
      { label: "Nam Tu Liem", value: EWard.namTuLiem },
      { label: "Bac Tu Liem", value: EWard.bacTuLiem },
      { label: "Tay Ho", value: EWard.tayHo },
      { label: "Cau Giay", value: EWard.cauGiay },
      { label: "Ha Dong", value: EWard.haDong },
    ],

    district: [
      { label: "Ba Vi", value: EDistrict.baVi },
      { label: "Chuong My", value: EDistrict.chuongMy },
      { label: "Phuc Tho", value: EDistrict.phucTho },
      { label: "Dan Phuong", value: EDistrict.danPhuong },
      { label: "Dong Anh", value: EDistrict.dongAnh },
      { label: "Gia Lam", value: EDistrict.giaLam },
      { label: "Hoai Duc", value: EDistrict.hoaiDuc },
      { label: "Me Linh", value: EDistrict.meLinh },
      { label: "My Duc", value: EDistrict.myDuc },
      { label: "Phu Xuyen", value: EDistrict.phuXuyen },
      { label: "Quoc Oai", value: EDistrict.quocOai },
      { label: "Soc Son", value: EDistrict.socSon },
      { label: "Thach That", value: EDistrict.thachThat },
      { label: "Thanh Oai", value: EDistrict.thanhOai },
      { label: "Thuong Tin", value: EDistrict.thuongTin },
      { label: "Ung Hoa", value: EDistrict.ungHoa },
      { label: "Thanh Tri", value: EDistrict.thanhTri },
    ],
  },
  shipmentType: [
    { label: "Received in store", value: EShipmentType.noShipment },
    { label: "Delivery", value: EShipmentType.delivery },
  ],
  paymentType: [
    { label: "Cash", value: EPaymentTypes.cash, icon: "../img/icon/cash.png" },
    {
      label: "Zalo - Pay",
      value: EPaymentTypes.zalo,
      icon: "../img/icon/zalo.png",
    },
    {
      label: "VIB - Bank",
      value: EPaymentTypes.vib,
      icon: "../img/icon/vib.png",
    },
  ],
  productStatus: [
    { label: "New", value: EProductStatus.new },
    { label: "90% new", value: EProductStatus.secondHand },
  ],
  inventoryStatus: [
    { label: "In stock", value: EInventoryStatus.inStock },
    { label: "Out of stock", value: EInventoryStatus.outOfStock },
  ],
  profit: [
    { label: "50%", value: EProfit.half },
    { label: "100%", value: EProfit.full },
  ],
  productCategory: [
    { label: "CPU", value: EProductType.cpu },
    { label: "RAM", value: EProductType.ram },
    { label: "VGA", value: EProductType.vga },
    { label: "HDD", value: EProductType.hdd },
    { label: "SSD", value: EProductType.ssd },
    { label: "PSU", value: EProductType.psu },
    { label: "MAINBOARD", value: EProductType.mainboard },
    { label: "MONITOR", value: EProductType.monitor },
    { label: "PRINTER", value: EProductType.printer },
    { label: "FAX", value: EProductType.fax },
    { label: "LAPTOP", value: EProductType.laptop },
    { label: "PC SET", value: EProductType.pcSet },
  ],
  producer: [
    { label: "ASUS", value: EProducer.asus },
    { label: "ASROCK", value: EProducer.asrock },
    { label: "GIGABYTE", value: EProducer.gigabyte },
    { label: "MSI", value: EProducer.msi },
    { label: "INTEL", value: EProducer.intel },
    { label: "AMD", value: EProducer.amd },
    { label: "SEAGATE", value: EProducer.seagate },
    { label: "WESTERN", value: EProducer.western },
    { label: "KINGSTON", value: EProducer.kingston },
    { label: "CORSAIR", value: EProducer.corsair },
    { label: "DEEPCOOL", value: EProducer.deepcool },
    { label: "COOLERMASTER", value: EProducer.coolermaster },
    { label: "DELL", value: EProducer.dell },
    { label: "HP", value: EProducer.hp },
    { label: "SAMSUNG", value: EProducer.samsung },
    { label: "LG", value: EProducer.lg },
    { label: "VIEWSONIC", value: EProducer.viewsonic },
  ],
};

export const optionsVn = {
  province: [
    { label: "Hồ Chí Minh", value: EProvince.HCM },
    { label: "Hà Nội", value: EProvince.HN },
  ],
  HCM: {
    ward: [
      { label: "1", value: EWard.one },
      { label: "2", value: EWard.two },
      { label: "3", value: EWard.three },
      { label: "4", value: EWard.four },
      { label: "5", value: EWard.five },
      { label: "6", value: EWard.six },
      { label: "7", value: EWard.seven },
      { label: "8", value: EWard.eight },
      { label: "9", value: EWard.nine },
      { label: "10", value: EWard.ten },
      { label: "11", value: EWard.eleven },
      { label: "12", value: EWard.twelve },
      { label: "13", value: EWard.thirteen },
      { label: "14", value: EWard.fourteen },
    ],
    district: [
      { label: "1", value: EDistrict.one },
      { label: "2", value: EDistrict.two },
      { label: "3", value: EDistrict.three },
      { label: "4", value: EDistrict.four },
      { label: "5", value: EDistrict.five },
      { label: "6", value: EDistrict.six },
      { label: "7", value: EDistrict.seven },
      { label: "8", value: EDistrict.eight },
      { label: "9", value: EDistrict.nine },
      { label: "10", value: EDistrict.ten },
      { label: "11", value: EDistrict.eleven },
      { label: "12", value: EDistrict.twelve },
    ],
  },
  HN: {
    ward: [
      { label: "Hoàn Kiếm", value: EWard.hoanKiem },
      { label: "Đống Đa", value: EWard.dongDa },
      { label: "Ba Đình", value: EWard.baĐinh },
      { label: "Hai Bà Trưng", value: EWard.haiBaTrung },
      { label: "Hoàng Mai", value: EWard.hoangMai },
      { label: "Thanh Xuân", value: EWard.thanhXuan },
      { label: "Long Biên", value: EWard.longBien },
      { label: "Nam Từ Liêm", value: EWard.namTuLiem },
      { label: "Bac Từ Liêm", value: EWard.bacTuLiem },
      { label: "Tây Hồ", value: EWard.tayHo },
      { label: "Cầu Giấy", value: EWard.cauGiay },
      { label: "Hà Đông", value: EWard.haDong },
    ],
    district: [
      { label: "Ba Vì", value: EDistrict.baVi },
      { label: "Chương Mỹ", value: EDistrict.chuongMy },
      { label: "Phúc Thọ", value: EDistrict.phucTho },
      { label: "Đan Phượng", value: EDistrict.danPhuong },
      { label: "Đông Anh", value: EDistrict.dongAnh },
      { label: "Gia Lâm", value: EDistrict.giaLam },
      { label: "Hoài Đức", value: EDistrict.hoaiDuc },
      { label: "Mê Linh", value: EDistrict.meLinh },
      { label: "Mỹ Đức", value: EDistrict.myDuc },
      { label: "Phú Xuyên", value: EDistrict.phuXuyen },
      { label: "Quốc Oai", value: EDistrict.quocOai },
      { label: "Sóc Sơn", value: EDistrict.socSon },
      { label: "Thạch Thất", value: EDistrict.thachThat },
      { label: "Thanh Oai", value: EDistrict.thanhOai },
      { label: "Thường Tín", value: EDistrict.thuongTin },
      { label: "Ứng Hoà", value: EDistrict.ungHoa },
      { label: "Thanh Trì", value: EDistrict.thanhTri },
    ],
  },
  shipmentType: [
    { label: "Nhận tại cửa hàng", value: EShipmentType.noShipment },
    { label: "Giao hàng tận nơi", value: EShipmentType.delivery },
  ],
  paymentType: [
    {
      label: "Tiền mặt",
      value: EPaymentTypes.cash,
      icon: "../img/icon/cash.png",
    },
    {
      label: "Ứng dụng Zalo - Pay",
      value: EPaymentTypes.zalo,
      icon: "../img/icon/zalo.png",
    },
    {
      label: "Ngân hàng quốc tế VIB",
      value: EPaymentTypes.vib,
      icon: "../img/icon/vib.png",
    },
  ],
  productStatus: [
    { label: "Mới", value: EProductStatus.new },
    { label: "Mới 90%", value: EProductStatus.secondHand },
  ],
  inventoryStatus: [
    { label: "Còn hàng", value: EInventoryStatus.inStock },
    { label: "Hết hàng", value: EInventoryStatus.outOfStock },
  ],
  profit: [
    { label: "50%", value: EProfit.half },
    { label: "100%", value: EProfit.full },
  ],
  productCategory: [
    { label: "CPU", value: EProductType.cpu },
    { label: "RAM", value: EProductType.ram },
    { label: "VGA", value: EProductType.vga },
    { label: "HDD", value: EProductType.hdd },
    { label: "SSD", value: EProductType.ssd },
    { label: "PSU", value: EProductType.psu },
    { label: "MAINBOARD", value: EProductType.mainboard },
    { label: "MONITOR", value: EProductType.monitor },
    { label: "PRINTER", value: EProductType.printer },
    { label: "FAX", value: EProductType.fax },
    { label: "LAPTOP", value: EProductType.laptop },
    { label: "PC SET", value: EProductType.pcSet },
  ],
  producer: [
    { label: "ASUS", value: EProducer.asus },
    { label: "ASROCK", value: EProducer.asrock },
    { label: "GIGABYTE", value: EProducer.gigabyte },
    { label: "MSI", value: EProducer.msi },
    { label: "INTEL", value: EProducer.intel },
    { label: "AMD", value: EProducer.amd },
    { label: "SEAGATE", value: EProducer.seagate },
    { label: "WESTERN", value: EProducer.western },
    { label: "KINGSTON", value: EProducer.kingston },
    { label: "CORSAIR", value: EProducer.corsair },
    { label: "DEEPCOOL", value: EProducer.deepcool },
    { label: "COOLERMASTER", value: EProducer.coolermaster },
    { label: "DELL", value: EProducer.dell },
    { label: "HP", value: EProducer.hp },
    { label: "SAMSUNG", value: EProducer.samsung },
    { label: "LG", value: EProducer.lg },
    { label: "VIEWSONIC", value: EProducer.viewsonic },
  ],
};

export const optionsCh = {
  province: [
    { label: "吴志明市", value: EProvince.HCM },
    { label: "河内市", value: EProvince.HN },
  ],
  HCM: {
    ward: [
      { label: "一", value: EWard.one },
      { label: "二", value: EWard.two },
      { label: "三", value: EWard.three },
      { label: "四", value: EWard.four },
      { label: "五", value: EWard.five },
      { label: "六", value: EWard.six },
      { label: "七", value: EWard.seven },
      { label: "八", value: EWard.eight },
      { label: "九", value: EWard.nine },
      { label: "十", value: EWard.ten },
      { label: "十一", value: EWard.eleven },
      { label: "十二", value: EWard.twelve },
      { label: "十三", value: EWard.thirteen },
      { label: "十四", value: EWard.fourteen },
    ],
    district: [
      { label: "一", value: EDistrict.one },
      { label: "二", value: EDistrict.two },
      { label: "三", value: EDistrict.three },
      { label: "四", value: EDistrict.four },
      { label: "五", value: EDistrict.five },
      { label: "六", value: EDistrict.six },
      { label: "七", value: EDistrict.seven },
      { label: "八", value: EDistrict.eight },
      { label: "九", value: EDistrict.nine },
      { label: "十", value: EDistrict.ten },
      { label: "十一", value: EDistrict.eleven },
      { label: "十二", value: EDistrict.twelve },
    ],
  },
  HN: {
    ward: [
      { label: "还剑", value: EWard.hoanKiem },
      { label: "东大", value: EWard.dongDa },
      { label: "巴亭", value: EWard.baĐinh },
      { label: "海巴中", value: EWard.haiBaTrung },
      { label: "黄迈", value: EWard.hoangMai },
      { label: "青春", value: EWard.thanhXuan },
      { label: "龙边", vbianalue: EWard.longBien },
      { label: "南都廉", value: EWard.namTuLiem },
      { label: "北都廉", value: EWard.bacTuLiem },
      { label: "西湖", value: EWard.tayHo },
      { label: "考嘉", value: EWard.cauGiay },
      { label: "河东", value: EWard.haDong },
    ],

    district: [
      { label: "巴维", value: EDistrict.baVi },
      { label: "章美", value: EDistrict.chuongMy },
      { label: "乐寿", value: EDistrict.phucTho },
      { label: "丹芳", value: EDistrict.danPhuong },
      { label: "东英", value: EDistrict.dongAnh },
      { label: "嘉林", value: EDistrict.giaLam },
      { label: "会德", value: EDistrict.hoaiDuc },
      { label: "美玲", value: EDistrict.meLinh },
      { label: "美德", value: EDistrict.myDuc },
      { label: "富雪", value: EDistrict.phuXuyen },
      { label: "国哇", value: EDistrict.quocOai },
      { label: "朔山", value: EDistrict.socSon },
      { label: "石七", value: EDistrict.thachThat },
      { label: "青哇", value: EDistrict.thanhOai },
      { label: "常识", value: EDistrict.thuongTin },
      { label: "配对", value: EDistrict.ungHoa },
      { label: "清治", value: EDistrict.thanhTri },
    ],
  },
  shipmentType: [
    { label: "在商店取货", value: EShipmentType.noShipment },
    { label: "交货", value: EShipmentType.delivery },
  ],
  paymentType: [
    { label: "现金", value: EPaymentTypes.cash, icon: "../img/icon/cash.png" },
    {
      label: "Zalo 应用程序 - 支付",
      value: EPaymentTypes.zalo,
      icon: "../img/icon/zalo.png",
    },
    {
      label: "VIB国际银行",
      value: EPaymentTypes.vib,
      icon: "../img/icon/vib.png",
    },
  ],
  productStatus: [
    { label: "全新", value: EProductStatus.new },
    { label: "90% 全新", value: EProductStatus.secondHand },
  ],
  inventoryStatus: [
    { label: "有存货", value: EInventoryStatus.inStock },
    { label: "缺货", value: EInventoryStatus.outOfStock },
  ],
  profit: [
    { label: "50%", value: EProfit.half },
    { label: "100%", value: EProfit.full },
  ],
  productCategory: [
    { label: "CPU", value: EProductType.cpu },
    { label: "RAM", value: EProductType.ram },
    { label: "VGA", value: EProductType.vga },
    { label: "HDD", value: EProductType.hdd },
    { label: "SSD", value: EProductType.ssd },
    { label: "PSU", value: EProductType.psu },
    { label: "MAINBOARD", value: EProductType.mainboard },
    { label: "MONITOR", value: EProductType.monitor },
    { label: "PRINTER", value: EProductType.printer },
    { label: "FAX", value: EProductType.fax },
    { label: "LAPTOP", value: EProductType.laptop },
    { label: "PC SET", value: EProductType.pcSet },
  ],
  producer: [
    { label: "ASUS", value: EProducer.asus },
    { label: "ASROCK", value: EProducer.asrock },
    { label: "GIGABYTE", value: EProducer.gigabyte },
    { label: "MSI", value: EProducer.msi },
    { label: "INTEL", value: EProducer.intel },
    { label: "AMD", value: EProducer.amd },
    { label: "SEAGATE", value: EProducer.seagate },
    { label: "WESTERN", value: EProducer.western },
    { label: "KINGSTON", value: EProducer.kingston },
    { label: "CORSAIR", value: EProducer.corsair },
    { label: "DEEPCOOL", value: EProducer.deepcool },
    { label: "COOLERMASTER", value: EProducer.coolermaster },
    { label: "DELL", value: EProducer.dell },
    { label: "HP", value: EProducer.hp },
    { label: "SAMSUNG", value: EProducer.samsung },
    { label: "LG", value: EProducer.lg },
    { label: "VIEWSONIC", value: EProducer.viewsonic },
  ],
};

type optionsEng = typeof optionsEng;
type optionsVn = typeof optionsVn;
type optionsCh = typeof optionsCh;

export type IOptionsLang = optionsEng | optionsCh | optionsVn | undefined;
