const VnLang = {
  headerMenu: {
    home: "Trang chủ",
    product: "Sản phẩm",
    course: "Khóa học",
    aboutUs: "Về chúng tôi",
    movie: "Phim",
    computer: "Máy tính PC",
    electronics: "Đồ điện tử",
    printer: "MÁY IN",
    faxMachine: "MÁY FAX",
    monitor: "MÀN HÌNH",
    cpu: "VI XỬ LÝ - CPU",
    ram: "BỘ NHỚ TẠM THỜI - RAM",
    hdd: "Ổ CỨNG - HDD",
    ssd: "Ổ CỨNG - SSD",
    vga: "CARD ĐỒ HỌA - VGA",
    psu: "NGUỒN MÁY TÍNH - PSU",
    mainboard: "MAINBOARD",
    accessories: "Linh kiện",
    mindsetProgramming: "Lập trình Tư Duy",
    mobileProgramming: "Lập trình Mobile",
    fullstackProgramming: "Lập trình Fullstack",
    backendProgramming: "Lập trình Backend",
    frontendProgramming: "Lập trình Frontend",
    signIn: "Đăng nhập",
    signUp: "Đăng ký",
    accountSetting: "Thông tin tài khoản",
    logOut: "Đăng xuất",
  },
  home: {
    carousel: {
      slideTitle_1: "LINH KIỆN MÁY TÍNH",
      slideContent_1: "Xây dựng máy tính dành riêng cho bạn",
      slideTitle_2: "KHÓA HỌC",
      slideContent_2: "Nâng cao kiến thức cho bản thân",
      slideTitle_3: "PHIM",
      slideContent_3: "Tận hưởng khoảnh khắc với gia đình",
    },
    consultation: {
      consultation: "Tư vấn",
      signUpConsultation: "Đăng ký tư vấn",
      modal: {
        title: "Thông tin người dùng",
        name: "Họ tên",
        email: "Email",
        phone: "Điện thoại",
        note: "Cảm ơn bạn đã quan tâm, chúng tôi đã nhận được thông tin của bạn, chúng tôi sẽ liên lạc với bạn sớm nhất. Trong lúc đó, hãy tiếp tục ghé thăm website của chúng tôi để biết thêm thông tin.",
      },
    },
    categories: {
      title_1: "Sản phẩm",
      title_2: "Khóa học",
      title_3: "Phim",
      content_1:
        "Được nhiều đối tác tin tưởng, Terra Nova chuyên cung cấp và phân phối các loại mặt hàng như điện tử, thiết bị gia dụng, phụ kiện máy tính, v.v.",
      content_2:
        "Với nhiều khóa học hấp dẫn, bạn có thể lựa chọn khóa học phù hợp với mình. Terra Nova sẽ làm hài lòng bạn.",
      content_3:
        "Terra Nova sẽ mang đến cho bạn những bộ phim hấp dẫn đến từ nhiều quốc gia.",
    },
    banner: {
      title_1: "LINH KIỆN MÁY TÍNH",
      title_2: "KHÓA HỌC",
      title_3: "PHIM",
      content_1: "Xây dựng máy tính dành riêng cho bạn",
      content_2: "Năng cao kiến thức cho bản thân",
      content_3: "Tận hưởng khoảnh khắc với gia đình",
      cpu: "Vi xử lý (CPU)",
      mainboard: "Bo mạch chủ",
      ram: "Bộ nhớ tạm thời (RAM)",
      hdd: "Ổ cứng (HDD, SSD)",
      vga: "Card đồ họa (VGA)",
      psu: "Nguồn máy tính (PSU)",
      monitor: "Màn hình",
      mindset: "Lập trình Tư Duy",
      frontend: "Lập trình Frontend",
      backend: "Lập trình Backend",
      mobile: "Lập trình Mobile",
      fullstack: "Lập trình Fullstack",
    },
    partners: {
      title: "Đối tác của chúng tôi",
      asusContent: `ASUSTek Computer Inc. Tiếng Trung: 華碩 電腦 股份有限公司; bính âm: Huáshuò Diànnǎo Gǔfèn Yǒuxiàn Gōngsī; viết tắt là ASUSTeK hoặc ASUS) là một công ty phần cứng và điện tử máy tính và điện thoại đa quốc gia của Đài Loan có trụ sở chính tại Quận Beitou, Đài Bắc, Đài Loan. Các sản phẩm của nó bao gồm máy tính để bàn, máy tính xách tay, netbook, điện thoại di động, thiết bị mạng, màn hình, bộ định tuyến wi-fi, máy chiếu, bo mạch chủ, card đồ họa, bộ lưu trữ quang, sản phẩm đa phương tiện, thiết bị ngoại vi, thiết bị đeo được, máy trạm máy chủ và máy tính bảng. Công ty cũng là nhà sản xuất thiết bị gốc (OEM).`,
      gigaContent: `Gigabyte Technology (có thương hiệu là GIGABYTE hoặc đôi khi là GIGA-BYTE; chính thức là GIGA-BYTE Technology Co., Ltd.) là một nhà sản xuất và phân phối phần cứng máy tính của Đài Loan. Hoạt động kinh doanh chính của Gigabyte là bo mạch chủ. Nó đã xuất xưởng 4,8 triệu bo mạch chủ trong quý đầu tiên của năm 2015, điều này cho phép họ trở thành nhà cung cấp bo mạch chủ hàng đầu. Gigabyte cũng sản xuất card đồ họa tùy chỉnh và máy tính xách tay (bao gồm cả máy tính xách tay mỏng và nhẹ dưới thương hiệu phụ Aero). Năm 2010, Gigabyte được Hội đồng Phát triển Ngoại thương Đài Loan xếp hạng thứ 17 trong “20 Thương hiệu Toàn cầu hàng đầu của Đài Loan”.`,
      msiContent: `Micro-Star International Co., Ltd (MSI; tiếng Trung: 微星 科技 股份有限公司) là một tập đoàn công nghệ thông tin đa quốc gia của Đài Loan có trụ sở chính tại thành phố Tân Đài Bắc, Đài Loan. Nó thiết kế, phát triển và cung cấp phần cứng máy tính, các sản phẩm và dịch vụ liên quan, bao gồm máy tính xách tay, máy tính để bàn, bo mạch chủ, card đồ họa Máy tính đa năng, máy chủ, máy tính công nghiệp, thiết bị ngoại vi PC, sản phẩm thông tin giải trí trên xe hơi, v.v.`,
      asrockContent: `ASRock Inc. (tiếng Trung: 華擎 科技 股份有限公司; bính âm: Huáqíng Kējì Gǔfèn Yǒuxiàn Gōngsī) là nhà sản xuất bo mạch chủ, PC công nghiệp và PC rạp hát tại nhà (HTPC) của Đài Loan. Được lãnh đạo bởi Ted Hsu, nó được thành lập vào năm 2002 và hiện thuộc sở hữu của công ty điện tử Pegatron của Đài Loan.`,
      kingstonContent: `Kingston Technology Corporation là một tập đoàn công nghệ máy tính đa quốc gia của Mỹ chuyên phát triển, sản xuất, bán và hỗ trợ các sản phẩm bộ nhớ flash và các sản phẩm bộ nhớ liên quan đến máy tính khác, cũng như bộ phận chơi game HyperX (hiện thuộc sở hữu của HP). Có trụ sở chính tại Fountain Valley, California, Hoa Kỳ, Kingston Technology sử dụng hơn 3.000 nhân viên trên toàn thế giới tính đến quý 1 năm 2016. Công ty có các cơ sở sản xuất và hậu cần tại Hoa Kỳ, Vương quốc Anh, Ireland, Đài Loan và Trung Quốc.`,
      westernContent: `Western Digital Corporation (WDC, thường được gọi là Western Digital hoặc WD) là một nhà sản xuất ổ đĩa cứng máy tính và công ty lưu trữ dữ liệu của Mỹ, có trụ sở chính tại San Jose, California. Nó thiết kế, sản xuất và bán các sản phẩm công nghệ dữ liệu, bao gồm thiết bị lưu trữ, hệ thống trung tâm dữ liệu và dịch vụ lưu trữ đám mây. Western Digital có lịch sử lâu đời trong ngành điện tử với tư cách là nhà sản xuất vi mạch tích hợp và công ty sản xuất sản phẩm lưu trữ. Đây là một trong những nhà sản xuất ổ đĩa cứng máy tính lớn nhất, cùng với việc sản xuất ổ SSD và thiết bị bộ nhớ flash. Các đối thủ cạnh tranh của nó bao gồm các công ty quản lý và lưu trữ dữ liệu Seagate Technology và Micron Technology.`,
      viewContent: `ViewSonic Corporation là một công ty điện tử đa quốc gia do tư nhân thành lập có trụ sở chính tại Brea, California, Hoa Kỳ và một trung tâm nghiên cứu & phát triển tại thành phố Tân Đài Bắc, Đài Loan. ViewSonic chuyên về phần cứng hiển thị hình ảnh — bao gồm màn hình tinh thể lỏng, máy chiếu và bảng tương tác — cũng như phần mềm bảng trắng kỹ thuật số. Công ty kinh doanh trên ba thị trường chính: giáo dục, doanh nghiệp và giải trí. ViewSonic là một doanh nghiệp thuộc sở hữu thiểu số được chứng nhận trên toàn quốc bởi Hội đồng phát triển nhà cung cấp cho người thiểu số Nam California.`,
      lgContent: `LG Corporation (hoặc LG Group) (tiếng Hàn: 엘지), trước đây là Lucky-Goldstar từ năm 1983 đến 1995 (tiếng Hàn: Leokki Geumseong; tiếng Hàn: 럭키 금성; Hanja: 樂 喜 金星), là một tập đoàn tập đoàn đa quốc gia của Hàn Quốc được thành lập bởi Koo In -hwoi và được quản lý bởi các thế hệ kế tiếp của gia đình mình. Đây là chaebol lớn thứ tư ở Hàn Quốc. Trụ sở chính của nó là tại tòa nhà LG Twin Towers ở Yeouido-dong, Quận Yeongdeungpo, Seoul. LG sản xuất các sản phẩm điện tử, hóa chất, viễn thông và điều hành các công ty con như LG Electronics, Zenith, LG Display, LG Uplus, LG Innotek, LG Chem và LG Energy Solution tại hơn 80 quốc gia.`,
      samsungContent: `Tập đoàn Samsung (hay đơn giản là Samsung) (tiếng Hàn: 삼성) là một tập đoàn sản xuất đa quốc gia của Hàn Quốc có trụ sở chính tại Samsung Town, Seoul, Hàn Quốc. Nó bao gồm nhiều doanh nghiệp trực thuộc, hầu hết trong số họ được hợp nhất dưới thương hiệu Samsung và là chaebol (tập đoàn kinh doanh) lớn nhất Hàn Quốc. Tính đến năm 2020, Samsung có giá trị thương hiệu toàn cầu cao thứ 8. Samsung được thành lập bởi Lee Byung-chul vào năm 1938 với tư cách là một công ty thương mại. Trong ba thập kỷ tiếp theo, tập đoàn này đã đa dạng hóa sang các lĩnh vực bao gồm chế biến thực phẩm, dệt may, bảo hiểm, chứng khoán và bán lẻ. Samsung tham gia vào ngành công nghiệp điện tử vào cuối những năm 1960 và ngành xây dựng và đóng tàu vào giữa những năm 1970; những lĩnh vực này sẽ thúc đẩy sự phát triển tiếp theo của nó. Sau khi Lee qua đời vào năm 1987, Samsung được tách thành 5 tập đoàn kinh doanh: Tập đoàn Samsung, Tập đoàn Shinsegae, Tập đoàn CJ và Tập đoàn Hansol, và Tập đoàn Joongang.`,
    },
    achievement: {
      branches: "Chi nhánh",
      customers: "Khách hàng",
      partners: "Đối tác",
    },
  },
  productList: {
    title: "SẢN PHẨM",
  },
  productDetail: {
    generalInfo: "Thông tin chung",
    producer: "Nhà sản xuất",
    warranty: "Bảo hành",
    status: "Tình trạng",
    price: "Giá",
    specs: "Thông số kỹ thuật",
    comments: "Bình luận",
    related: "Sản phẩm liên quan",
  },
  footer: {
    partners: "Đối tác",
    socials: "Nền tảng",
    company: "CÔNG TY THƯƠNG MẠI TERRA NOVA",
    address_1:
      "Chi nhánh 1: 102 Nguyễn Đình Chính, Phường 15, Quận Phú Nhuận, TP.HCM",
    address_2:
      "Chi nhánh 2: 12B Nguyễn Hữu Cảnh, Phường 19, Quận Bình Thạnh, TP.HCM",
  },
  productCarts: {
    title: "Giỏ hàng",
    summaryTitle: "Thông tin chung",
    choosePaymentType: "Chọn hình thức thanh toán",
    paymentType: "Hình thức thanh toán",
    payment: "Thanh toán",
    note: "Ghi chú",
    price: "Giá",
    shipment: "Phí giao hàng",
    total: "Tổng cộng",
    vat: "Thuế VAT 10%",
    totalPay: "Thành tiền",
    receivedType: "Chọn hình thức nhận hàng",
    modal: {
      shipmentTitle: "Thông tin vận chuyển",
      paymentTitle: "Thành toán thành công",
      orderTitle: "Thông tin đặt hàng",
      product: "Thông tin sản phẩm",
      shipment: "Thông tin giao hàng",
      receiver: "Người nhận",
      orderer: "Người đặt",
      address: "Địa chỉ giao hàng",
      note: "Chú ý: Vui lòng cung cấp thông tin chính xác tránh các vấn đề phát sinh và để việc vận chuyển thuận tiện hơn",
    },
  },
  aboutUs: {
    banner: {
      title: "Giới thiệu về",
    },
    intro: {
      intro_1:
        "Mong muốn tạo ra một nền tảng để khách hàng có thể trải nghiệm và sử dụng các dịch vụ trực tuyến chất lượng, Terra Nova ra đời nhằm đáp ứng những nhu cầu đó.",
      intro_2:
        "Terra Nova được thành lập ngày 28 tháng 11 năm 2010. Với tầm nhìn trở thành nền tảng phổ biến với người dùng, sau hơn 10 năm nỗ lực, Terra nova ngày càng được các đối tác và khách hàng tin tưởng.",
        subTitle: "Các sản phẩm và dịch vụ của chúng tôi",
        product: "Sản phẩm điện tử và linh kiện máy tính",
        course: "Khóa học",
        service: "Dịch vụ đặt vé xem phim trực tuyến",
    },
    vision: {
      title: "Tầm nhìn của chúng tôi",
      content: "Mang đến cho bạn một nền tảng phổ biến, tiện dụng và thân thiện",
    },
    mission: {
      title: "Nhiệm vụ của chúng tôi",
      content: "Chúng tôi cung cấp nền tảng nơi bạn có thể sử dụng các dịch vụ như mua sản phẩm, khóa học hoặc đặt vé xem phim trực tuyến, v.v"
    },
  },
  user: {
    hello: "Xin chào",
    overviewTitle: "Tổng quan",
    accountInfo: "Thông tin tài khoản",
    personalInfo: "Thông tin cá nhân",
    orderTitle: "Danh sách đơn hàng",
  },
  time: {
    day: "ngày",
    month: "tháng",
    year: "năm",
    days: "ngày",
    months: "tháng",
    years: "năm",
    Day: "Ngày",
    Month: "Tháng",
    Year: "Năm",
    Days: "Ngày",
    Months: "Tháng",
    Years: "Năm",
  },
  status: {
    new: "Mới 100%",
    paid: "Đã thanh toán",
    stocking: "Còn hàng",
    outOfStock: "Hết hàng", 
  },
  paymentType: {
    cash: "Tiền mặt",
    zalo: "Ứng dụng Zalo - pay",
    vib: "Ngân hàng quốc tế VIB",
  },
  shipmentType: {
    noShipment: "Nhận tại cửa hàng",
    delivery: "Giao hàng tận nơi",
  },
  button: {
    submit: "Gửi",
    seeMore: "Xem thêm",
    addToCart: "Thêm vào giỏ hàng",
    buyProduct: "Mua sản phẩm",
    continueBuy: "Tiếp tục mua hàng",
    addProduct: "Tạo sản phẩm",
    update: "Cập nhật",
    payment: "Thanh toán",
  },
  noData: {
    data: "Không tìm thấy dữ liệu",
    product: "Chưa có sản phẩm",
    order: "Chưa có đơn hàng",
  },
  carts: {
    slots: "sl",
    total: "Tổng cộng",
  },
  toastMessages: {
    success: {
      addToCart: "Thêm vào giỏ hàng thành công",
      updateCart: "Cập nhật thành công",
      removeCart: "Xóa thành công",
      createOrder: "Thanh toán thành công",
      signIn: "Đăng nhập thành công",
      signUp: "Đăng ký thành công",
    },
    error: {
      addToCart: "Thêm vào giỏ hàng thất bại",
      updateCart: "Cập nhật thất bại",
      removeCart: "Xóa thất bại",
      createOrder: "Thanh toán thất bại",
      signIn: "Tài khoản hoặc mật khẩu không đúng",
      signUp: "Đăng ký thất bại",
      onlyNumber: "Chỉ có thể nhập số",
    },
  },
  validateMessages: {
    required: "Vui lòng không bỏ trống",
    date: "Vui lòng chọn ngày",
    phone: "Điện thoại không hợp lệ",
    email: "Email không hợp lệ",
    password: "Mật khẩu không đúng",
    gender: "Vui lòng chọn giới tính",
    whiteSpace: "Không được có khoảng trắng giữa các ký tự",
  },
  form: {
    account: "Tài khoản",
    password: "Mật khẩu",
    passConfirm: "Xác nhận mật khẩu",
    name: "Họ tên",
    firstName: "Tên",
    lastName: "Họ",
    email: "Địa chỉ email",
    phone: "Số điện thoại",
    address: "Địa chỉ",
    birthday: "Sinh nhật",
    gender: "Giới tính",
    male: "Nam",
    female: "Nữ",
    comment: "Ghi chú",
    personalInfo: "Thông tin cá nhân",
    signIn: "Đăng nhập",
    signUp: "Đăng ký",
    dontHaveAcc: "Bạn chưa có tài khoản?",
    haveAcc: "Bạn đã có tài khoản?",
    search: "Tìm kiếm",
    note: "Ghi chú",
    ward: "Phường/Huyện",
    district: "Quận",
    province: "Tỉnh/Thành phố",
    selectWard: "Chọn phường/huyện",
    selectDistrict: "Chọn quận",
    selectProvince: "Chọn tỉnh/thành phố",
    noOption: "Không có dữ liệu",
    defaultOption: "Chọn...",
  },
  tableHeader: {
    number: "STT",
    image: "Hình ảnh",
    name: "Họ Tên",
    productName: "Tên sản phẩm",
    amount: "Số lượng",
    price: "Đơn giá",
    features: "Chức năng",
    description: "Mô tả",
    total: "Tổng cộng",
    orderId: "Mã Đơn hàng",
    orderStatus: "Tình trạng",
    paymentType: "Thanh toán",
    totalPay: "Tổng tiền",
    products: "Sản phẩm",
    createdAt: "Ngày tạo"
  },
  pagination: {
    showing: "Hiển thị",
    of: "của",
    results: "kết quả",
  },
};

export type LangVN = typeof VnLang;

export default VnLang;
